version: '3.3'

services:
 php:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: php73
  depends_on:
   - db
  image: php:7.3-apache
  volumes:
   - .:/var/www/html/
  ports:
   - 8082:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: mvc
   MYSQL_USER: user
   MYSQL_PASSWORD: password
  ports:
   - 3307:3306
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   PMA_USER: myuser
   PMA_PASSWORD: monpassword
   UPLOAD_LIMIT: 20M
  ports:
   - 8899:80
